### PR TITLE
Week1

### PR DESCRIPTION
**Pull request by akash-more**
Added Assignment 1 for Week 1, how browser works and Assignment 2 for Week 1 for creating a static HTML page as per the mockup.

### CODE REVIEW

**Comment by akash-more** [comment]
Below is how the static HTML page looks like
image

**Comment by anilrao316** [comment]
Going forward lets follow BEM naming conventions for classes http://getbem.com/naming/

**Comment by anilrao316** [comment]
Rest looks good!

**Comment by akash-more** [comment]
@anilrao316 thanks for the review.

**Pull request merged**
